### PR TITLE
Use linux/types.h for byte order types

### PR DESCRIPTION
**Pull request by jdinan**
Fix the following build error by using `linux/types.h` when available:
```
$ make
Making all in doc
make[1]: Entering directory `/home/dinanjam/projects/portals4/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/dinanjam/projects/portals4/doc'
Making all in include
make[1]: Entering directory `/home/dinanjam/projects/portals4/include'
make  all-am
make[2]: Entering directory `/home/dinanjam/projects/portals4/include'
make[2]: Leaving directory `/home/dinanjam/projects/portals4/include'
make[1]: Leaving directory `/home/dinanjam/projects/portals4/include'
Making all in src
make[1]: Entering directory `/home/dinanjam/projects/portals4/src'
Making all in ib
make[2]: Entering directory `/home/dinanjam/projects/portals4/src/ib'
  CC       libportals_ib_la-ptl_atomic.lo
In file included from ptl_loc.h:53:0,
                 from ptl_atomic.c:7:
ptl_byteorder.h:7:18: error: conflicting types for '__be64'
 typedef uint64_t __be64;
                  ^
In file included from /usr/include/infiniband/verbs.h:44:0,
                 from /usr/include/rdma/rdma_cma.h:39,
                 from ptl_loc.h:47,
                 from ptl_atomic.c:7:
/usr/include/linux/types.h:32:25: note: previous declaration of '__be64' was here
 typedef __u64 __bitwise __be64;
                         ^
In file included from ptl_loc.h:53:0,
                 from ptl_atomic.c:7:
ptl_byteorder.h:10:18: error: conflicting types for '__le64'
 typedef uint64_t __le64;
                  ^
In file included from /usr/include/infiniband/verbs.h:44:0,
                 from /usr/include/rdma/rdma_cma.h:39,
                 from ptl_loc.h:47,
                 from ptl_atomic.c:7:
/usr/include/linux/types.h:31:25: note: previous declaration of '__le64' was here
 typedef __u64 __bitwise __le64;
                         ^
make[2]: *** [libportals_ib_la-ptl_atomic.lo] Error 1
make[2]: Leaving directory `/home/dinanjam/projects/portals4/src/ib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dinanjam/projects/portals4/src'
make: *** [all-recursive] Error 1
```

### CODE REVIEW

**Comment by jdinan** [comment]
@regrant Could you take a look at this PR?  Thanks!

**Comment by raffenet** [comment]
👍 this fixes the build on CentOS 7.6 for me.
