### ISSUE TITLE
Linking fails due to multiple declaration of abort state

### ISSUE THREAD

**Issue by markbrown314** [Portals4/portals4#99]
The abort_state global variable was introduced in #98 and declared in the header file:  src/ib/ptl_gbl.h:27

```C
struct ptl_abort_state abort_state;
```
On Ubuntu 24.04 libtool will fail with the error:

```
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2 -mcx16 -version-info 4:0:0 -no-undefined -Wl,--version-script=./ib/portals4.map  -o libportals.la -rpath /usr/local/lib  ib/libportals_ib.la -lhwloc -ldl                                                                                                                                                                                                                  libtool: link: gcc -shared  -fPIC -DPIC  -Wl,--whole-archive ib/.libs/libportals_ib.a -Wl,--no-whole-archive  -lev -lm -lpthread -lhwloc -ldl  -g -O2 -mcx16 -Wl,--version-script=./ib/portals4.map   -Wl,-soname -Wl,libportals.so.4 -o .libs/libportals.so.4.0.0
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_buf.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_conn.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_ct.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_ct_common.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_data.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
/usr/bin/ld: ib/.libs/libportals_ib.a(libportals_ib_la-ptl_eq.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: multiple definition of `abort_state'; ib/.libs/libportals_ib.a(libportals_ib_la-ptl_atomic.o):/home/sdp/portals4/src/ib/ptl_gbl.h:27: first defined here
```

abort_state should be declared once in a .c file preferably and src/ib/ptl_gbl.h:27 should be changed to:
```C
extern struct ptl_abort_state abort_state;
```

configure flags:
./configure --enable-zero-mrs --enable-reliable-udp --disable-pmi-from-portals
